version: '3'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      DATABASE_URL: "mysql://root:root_password@mysql:3306/stockbot?serverVersion=8.0&charset=utf8mb4"
    depends_on:
      - mysql
    restart: always

  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: stockbot
      MYSQL_ROOT_PASSWORD: root_password