version: '3'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      DATABASE_URL: "mysql://root:root_password@mysql:3307/stockbot"
    depends_on:
      - mysql

  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: stockbot
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"